### ISSUE TITLE
Can not downgrade pwnedDFU iPhone 4s

### ISSUE THREAD

**Issue by leon47331** [LukeZGD/iOS-OTA-Downgrader#166]
Hello,

I wanna downgrade my iPhone 4s to iOS 6.
I successfully put the iPhone in kDFU / pwnDFU with the Arduino.

Now when I run the script, it runs as following:

```
leon@MacBook-Pro-von-Leon iOS-OTA-Downgrader-main % ./restore.sh PwnedDevice
******* iOS-OTA-Downgrader ******* 
   Downgrader script by LukeZGD    

[Log] Running on platform: macos (12.0.1) 
[Log] Checking Internet connection... 
[Log] Apple Silicon Mac detected. Support may be limited, proceed at your own risk. 
[Log] Finding device in Normal mode... 
[Log] Finding device in DFU/recovery mode... 
[Log] iPhone4,1 connected in DFU mode. 
[Log] ECID: 94823423034 
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade Device	      4) (Re-)Install Dependencies
2) Save OTA Blobs	      5) (Any other key to exit)
3) Create Custom IPSW
#? 1

[Input] Select iOS version: 
1) iOS 8.4.1		    3) Other (use SHSH blobs)
2) iOS 6.1.3		    4) (Any other key to exit)
#? 2

* DFU Advanced Menu 
* This menu is for ADVANCED USERS ONLY. 
* If you do not know what you are doing, EXIT NOW by pressing Ctrl+C and restart your device in normal mode. 
[Input] Select the mode that your device is currently in: 
1) kDFU mode
2) pwnDFU mode (A5)
3) Any other key to exit
#? 2
* Make sure that your device is in pwnDFU mode using an Arduino+USB Host Shield! 
* This option will not work if your device is not in pwnDFU mode. 
[Input] Press Enter/Return to continue (or press Ctrl+C to cancel) 
[Log] Patching iBSS... 
[Log] Sending iBSS... 
Traceback (most recent call last):
  File "ipwndfu", line 85, in <module>
    device = usbexec.PwnedUSBDevice()
  File "/Users/Leon/Downloads/iOS-OTA-Downgrader-main/resources/ipwndfu/usbexec.py", line 137, in __init__
    device = dfu.acquire_device()
  File "/Users/Leon/Downloads/iOS-OTA-Downgrader-main/resources/ipwndfu/dfu.py", line 16, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Users/Leon/Downloads/iOS-OTA-Downgrader-main/resources/ipwndfu/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
[Log] Downgrading iPhone4,1 in kDFU/pwnDFU mode... 
[Log] Select your options when asked. If unsure, go for the defaults (press Enter/Return). 

[Input] Jailbreak Option 
* When this option is enabled, your device will be jailbroken on restore. 
* This option is enabled by default (Y). 
[Input] Enable this option? (Y/n): y
[Log] Jailbreak option enabled. Using p0sixspwn for the jailbreak 

[Log] Checking signing status of iOS 9.3.6... 
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
[TSSC] manually specified ECID to use, parsed "948014837034" to dec:948014837034 hex:dcba166d2a
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 9.3.6 build 13G37
[TSSC] opening Buildmanifest for iPhone4,1_9.3.6_13G37
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
Saved shsh blobs!
Firmware version 9.3.6 13G37 IS signed!

iOS 9.3.6 for device iPhone4,1 IS being signed!
[Log] Latest version for iPhone4,1 (iOS 9.3.6) is signed. 
[Log] Saving iOS 6.1.3 blobs with tsschecker... 
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "948014837034" to dec:948014837034 hex:dcba166d2a
[TSSC] opening resources/manifests/BuildManifest_iPhone4,1_6.1.3.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[Error] [TSSR] Error: could not get id0 for installType=Erase
Saved shsh blobs!

iOS 6.1.3 for device iPhone4,1 IS being signed!
[Log] Successfully saved 6.1.3 blobs. 
[Log] Found existing Custom IPSW. Skipping IPSW verification. 
[Log] Setting restore IPSW to: iPhone4,1_6.1.3_10B329_Custom.ipsw 
[Log] Found existing Custom IPSW. Skipping IPSW creation. 
[Log] Extracting IPSW: iPhone4,1_6.1.3_10B329_Custom.ipsw 
[Log] Proceeding to futurerestore... 
Version: v2.0.0-test(a58821b95f6417ad649ed7a5460337dcd82e200e-259)
img4tool version: 0.197+git20210129-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.86+git20210810-6a3b358b673e74c2be9f9b8a74a63b80dd94abf1-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
[INFO] 32-bit device detected
futurerestore init done
reading signing ticket 948014837034_iPhone4,1_n94ap_6.1.3-10B329_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2 is done
Did set SEP+baseband path and firmware
ERROR: Unable to connect to device?!
ERROR: Unable to get FirmwarePreflightInfo
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening saved/iPhone4,1/BuildManifest.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Serving HTTP on 0.0.0.0 port 8888 ...
Sending TSS request attempt 1... response successfully received
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as n94ap, iPhone4,1
Extracting BuildManifest from iPSW
Product version: 6.1.3
Product build: 10B329 Major: 10
Device supports Image4: false
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[WARNING] skipping ramdisk hash check, since device is in pwnDFU according to user
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Device found in DFU Mode.
Getting firmware keys for: n94ap
127.0.0.1 - - [09/Mar/2022 12:32:12] "GET /firmware/iPhone4,1/10B329 HTTP/1.1" 301 -
127.0.0.1 - - [09/Mar/2022 12:32:12] "GET /firmware/iPhone4,1/10B329/ HTTP/1.0" 200 -
127.0.0.1 - - [09/Mar/2022 12:32:12] "GET /firmware/iPhone4,1/10B329 HTTP/1.1" 301 -
127.0.0.1 - - [09/Mar/2022 12:32:12] "GET /firmware/iPhone4,1/10B329/ HTTP/1.0" 200 -
Sending iBEC (276760 bytes)...
Cleaning up...
[exception]:
what=ERROR: Unable to send iBEC component: Unable to upload data to device

code=39845905
line=608
file=futurerestore.cpp
commit count=259:
commit sha  =a58821b95f6417ad649ed7a5460337dcd82e200e:
Done: restoring failed!

[Log] Restoring done! 
[Log] Downgrade script done! 
```

What can I do now?
Thank you in advance :)

**Comment by LukeZGD** [comment]
I have updated ipwndfu just now to attempt fixing this. Please try again by deleting ipwndfu in the resources folder then attempt to downgrade again

**Comment by leon47331** [comment]
Thank you for your response :)
But that doesn't work for me either.

What has worked for me was to run the script on Intel Mac. It still gave me the same error when I try to run it on my M1 MacBook :)

**Comment by LukeZGD** [comment]
Oh, yeah ipwndfu is not supported on Apple Silicon Macs, this will not be fixed sorry
