### ISSUE TITLE
Unable to get past 80.9% on sending iBEC (iPhone 5s Global, MacBook Air M1, macOS 13.2)

### ISSUE THREAD

**Issue by JoshAtticus** [LukeZGD/iOS-OTA-Downgrader#252]
Can't get past 80.9%, just keeps retrying. Have tried restarting, using gaster and ipwndfu, and using a different cable, but it just doesn't work.

Logs:
```
*** Main Menu ***
[Input] Select an option:
1) Downgrade Device	      4) (Re-)Install Dependencies
2) Save OTA Blobs	      5) (Any other key to exit)
3) Create Custom IPSW
#? 1

[Input] Select iOS version:
1) 10.3.3		    3) (Any other key to exit)
2) Other (use SHSH blobs)
#? 1
[Log] Found existing Custom IPSW. Skipping 10.3.3 IPSW verification.
[Log] Patching iBSS and iBEC...
Archive:  ../iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBSS.iphone6.RELEASE.im4p  
Archive:  ../iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBEC.iphone6.RELEASE.im4p  
[Log] Pwned iBSS and iBEC saved at: saved/iPhone6,2
* Get ready to enter DFU mode.
[Input] Select Y to continue, N to exit recovery mode (Y/n) Y
* Hold TOP and HOME buttons for 10 seconds.
10 09 08 07 06 05 04 03 02 01 
* Release TOP button and hold HOME button for 8 seconds.
08 07 06 05 04 03 02 01 
[Log] Finding device in DFU mode...
[Log] Found device in DFU mode.
[Input] PwnDFU Tool Option
* Select tool to be used for entering pwned DFU mode.
* This option is set to ipwnder by default (1).
[Input] Select your option:
1) ipwnder
2) gaster
#? 2
[Log] Placing device to pwnDFU mode using: ../bin/macos/gaster pwn
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Now you can boot untrusted images.
[Log] python2 from pyenv detected
~/Repos/iOS-OTA-Downgrader/resources/ipwndfu ~/Repos/iOS-OTA-Downgrader/tmp ~/Repos/iOS-OTA-Downgrader
[Log] Running rmsigchks...
*** SecureROM Signature check remover by Linus Henze ***
Traceback (most recent call last):
  File "rmsigchks.py", line 92, in <module>
    main()
  File "rmsigchks.py", line 62, in main
    device = dfu.acquire_device()
  File "/Users/josh/Repos/iOS-OTA-Downgrader/resources/ipwndfu/dfu.py", line 16, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Users/josh/Repos/iOS-OTA-Downgrader/resources/ipwndfu/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
~/Repos/iOS-OTA-Downgrader/tmp ~/Repos/iOS-OTA-Downgrader
[Log] Found existing saved 10.3.3 blobs: ../saved/shsh/6101189033744_iPhone6,2_n53ap_10.3.3-14G60_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2
[Log] Entering pwnREC mode... (Attempt 1)
[Log] Sending iBSS...
[==================================================] 100.0%
[Log] Sending iBEC...
[=========================================         ] 80.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Log] Entering pwnREC mode... (Attempt 2)
[Log] Sending iBSS...
[Log] Sending iBEC...
[=========================================         ] 80.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Log] Entering pwnREC mode... (Attempt 3)
[Log] Sending iBSS...
[Log] Sending iBEC...
[=========================================         ] 80.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Log] Entering pwnREC mode... (Attempt 4)
[Log] Sending iBSS...
[Log] Sending iBEC...
[=========================================         ] 80.9%[Log] Finding device in Recovery mode...
* You may also try to unplug and replug your device
[Error] Failed to enter pwnREC mode. You may have to force restart your device and start over entering pwnDFU mode again

josh@Joshs-MacBook-Air iOS-OTA-Downgrader % 
```

**Comment by LukeZGD** [comment]
Try selecting ipwnder instead, or try other tools like LeetDown since that has better support for ASi Macs

**Comment by JoshAtticus** [comment]
Alright! Thanks for your help!
